# Author: liubin
# Create Date: 2017-06-21
# Description: api
#
# 接口控制格式 参数说明
# login: 登陆模块
# index: 首页模块
#region   地域模块
#spec     规格模块
#agree    履约模块
#report   固定格式报表
# httpmethod: 请求类型
# routepath: 请求接口[统一加前缀][/api/tztx]
# authorized: 是否已授权
# description: 接口描述
# enableroute: 是否已废弃
# responetype: 接口返回格式
#
test:                                       # 测试
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/test/datScanTimes'
    authorized: 1
    description: 'test'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
login:                                      # 登录
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/admin/login/verification'
    authorized: 1
    description: '登陆'
    enableroute: 1
    gatewaytype: 1
    responetype: 'json'
  - httpmethod: 'get'
    routepath: '/api/tztx/saas/Kaptcha.validatecode'
    authorized: 1
    description: '验证码'
    enableroute: 1
    gatewaytype: 1
    responetype: 'json'
menu:
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/menu/user_list_moudle'
    authorized: 1
    description: '顶部导航'
    enableroute: 1
    gatewaytype: 1
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/menu/user_list_menu'
    authorized: 1
    description: '左侧菜单'
    enableroute: 1
    gatewaytype: 1
    responetype: 'json'
index:                                      # 首页
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/login/user_detail'
    authorized: 1
    description: '用户信息'
    enableroute: 1
    gatewaytype: 1
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/dayScanTimes'
    authorized: 1
    description: '当日扫码次数'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/dayScanUsers'
    authorized: 1
    description: '当日扫码人数'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/dayScanCodes'
    authorized: 1
    description: '当日扫码烟包数'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getScanData'
    authorized: 1
    description: '历史扫码数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/rollingData'
    authorized: 1
    description: '滚动数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/topTen'
    authorized: 1
    description: '前10'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/getProvinceKPI'
    authorized: 1
    description: '销区指标'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/getSpecificationKPI'
    authorized: 1
    description: '规格指标'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/firstTimeScan'
    authorized: 1
    description: '销区与规格'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/getCityKPI'
    authorized: 1
    description: '获取城市'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/data/mapdata'
    authorized: 1
    description: '地图数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
region:
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getProvince'
    authorized: 1
    description: '省份下拉列表'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getWeeks'
    authorized: 1
    description: '周下拉列表'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesHourTrend'
    authorized: 1
    description: '时刻分析图'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getScanData'
    authorized: 1
    description: '仪表盘'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesOfProvAndSpec'
    authorized: 1
    description: '各规格扫码次数'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesOfCity'
    authorized: 1
    description: '地市'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesTrend'
    authorized: 1
    description: '扫码次数时间趋势'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanCodesOfProvince'
    authorized: 1
    description: '扫码包数'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
spec:
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getProduct'
    authorized: 1
    description: '规格'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getWeeks'
    authorized: 1
    description: '周下拉列表'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/specificationKPI'
    authorized: 1
    description: '新增扫码数'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesHourTrend'
    authorized: 1
    description: '时刻分析图'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getMapData'
    authorized: 1
    description: '地图'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesOfCityAndSpec'
    authorized: 1
    description: '地市'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getAwardDistribute'
    authorized: 1
    description: '奖品'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/scanTimesTrendOfSpec'
    authorized: 1
    description: '扫码次数时间趋势'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/drawTimesTrendOfSpec'
    authorized: 1
    description: '奖品领取'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
agree:
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getOtherResouce'
    authorized: 1
    description: '异业'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getOtherResouceCount'
    authorized: 1
    description: '异业分页'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getPrize'
    authorized: 1
    description: '现金奖品'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getPrizeCount'
    authorized: 1
    description: '奖品发放数量'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getBrand'
    authorized: 1
    description: '品牌'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
visit:
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getFeedBack'
    authorized: 1
    description: '回访记录'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/feedbackCount'
    authorized: 1
    description: '回访数量'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/updateFeddBackStatus'
    authorized: 1
    description: '更新回访'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
report:
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/fixatreport/getWinUseProvData'
    authorized: 1
    description: '中奖用户地域情况数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/fixatreport/getScanUseProvData'
    authorized: 1
    description: '扫码用户地域情况'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/fixatreport/getDailySummaryData'
    authorized: 1
    description: '日报汇总表数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getProductOfNoNuit'
    authorized: 1
    description: '扫码规格'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getProduct'
    authorized: 1
    description: '中奖规格'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
multi:
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getQueryRecord'
    authorized: 1
    description: '历史查询接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/saveQueryRecord'
    authorized: 1
    description: '保存查询接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getProvince'
    authorized: 1
    description: '获取省'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getCitysByProvince'
    authorized: 1
    description: '根据省获取市'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getProductOfNoNuit'
    authorized: 1
    description: '获取规格'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getBrand'
    authorized: 1
    description: '根据规格获取品牌'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getMultiScanData'
    authorized: 1
    description: '扫码表格数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getMultiCashData'
    authorized: 1
    description: '现金表格数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getMultiGoodData'
    authorized: 1
    description: '实物表格数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getMultiKPIData'
    authorized: 1
    description: '指标表格数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getPrize'
    authorized: 1
    description: '现金奖品'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/dataportal/statistics/getPrizeCount'
    authorized: 1
    description: '奖品发放数量'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
manageacts:
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/activity/list'
    authorized: 1
    description: '活动列表查询接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/activity/update'
    authorized: 1
    description: '活动增加接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/queryDimActivatyForm'
    authorized: 1
    description: '查询活动形式维度信息'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/template/template_common_list'
    authorized: 1
    description: '公用模板列表接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/queryRegionByParentCode'
    authorized: 1
    description: '根据父地区编码查询数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/queryAllRegion'
    authorized: 1
    description: '查询所有地区数据'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/querySupplier'
    authorized: 1
    description: '根据厂商获取供应商接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/queryBrand'
    authorized: 1
    description: '根据供应商获取品牌接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/queryProduct'
    authorized: 1
    description: '根据品牌获取规格接口'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/queryDimDataStatus'
    authorized: 1
    description: '查询活动状态'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/brand/queryBrands'
    authorized: 1
    description: '查询所有品牌'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/product/queryMetraList'
    authorized: 1
    description: '根据条件分页查询物料（礼品、红包）列表'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/common/commonUpload'
    authorized: 1
    description: '文件上传到阿里云服务器'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/poolGift/addPool'
    authorized: 1
    description: '礼品增库'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
  - httpmethod: 'post'
    routepath: '/api/tztx/saas/saotx/poolRedpack/addPool'
    authorized: 1
    description: '红包增库'
    enableroute: 1
    gatewaytype: 0
    responetype: 'json'
