# Author: liubin
# Create Date: 2017-06-21
# Description: view
#
# 接口控制格式 参数说明
# login: 登陆模块
# index: 首页模块
# httpmethod: 请求类型
# routepath: 请求接口
# authorized: 是否已授权
# description: 接口描述
# enableroute: 是否已废弃
# responetype: 接口返回格式
# staticfile: 文件名称
#
login:                                      # 登录
  - httpmethod: 'get'
    routepath: '/login'
    description: '登陆页面'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'login.html'
  - httpmethod: 'get'                       # 找回密码
    routepath: '/find'
    description: '登陆页面'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'find.html'
home:                                       # 首页
  - httpmethod: 'get'                       # KPI
    routepath: '/view/home/kpi'
    description: 'kpi'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/kpi/kpi.html'
  - httpmethod: 'get'                       # KPI
    routepath: '/view/home/henan-kpi'
    description: 'kpi'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/kpi/kpi-henan.html'
  - httpmethod: 'get'                       # KPI总指标
    routepath: '/view/home/theme/overall'
    description: 'theme'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/theme/overall.html'
  - httpmethod: 'get'                       # 主题查询[规格]
    routepath: '/view/home/theme/spec'
    description: 'theme'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/theme/spec.html'
  - httpmethod: 'get'                       # 主题查询[地域]
    routepath: '/view/home/theme/region'
    description: 'theme'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/theme/region.html'
  - httpmethod: 'get'                       # 多维查询
    routepath: '/view/home/multi'
    description: 'multidimension'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/multi/multi.html'
  - httpmethod: 'get'                       # 活动实时跟踪
    routepath: '/view/home/realtime'
    description: 'realtime'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/track/realtime.html'
  - httpmethod: 'get'                       # 用户群体分析
    routepath: '/view/home/user/group'
    description: 'user'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/user/group.html'
  - httpmethod: 'get'                       # 用户全息画像s
    routepath: '/view/home/user/portrait'
    description: 'user'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/user/portrait.html'
  - httpmethod: 'get'                       # 用户全息画像s
    routepath: '/view/home/user/labelmanage'
    description: 'user'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/user/labelmanage.html'
  - httpmethod: 'get'                       # 活动日常分析
    routepath: '/view/home/dayanalysis'
    description: 'dayanalysis'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/track/dayanalysis.html'
  - httpmethod: 'get'                       # 页面路径转化信息
    routepath: '/view/home/pathdetail'
    description: 'pathdetail'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/track/pathdetail.html'
  - httpmethod: 'get'                       # 零售户
    routepath: '/view/home/retailer/overview'
    description: 'retailer'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/retailer/overview.html'
  - httpmethod: 'get'                       # 零售户详情
    routepath: '/view/home/retailer/detail'
    description: 'retailer'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/retailer/detail.html'
  - httpmethod: 'get'                       # 零售户分析
    routepath: '/view/home/retailer/analysis'
    description: 'retailer'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/retailer/analysis.html'
  - httpmethod: 'get'                       # 报表导出
    routepath: '/view/home/report'
    description: 'report'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/report/report.html'
  - httpmethod: 'get'                       # 河南报表导出
    routepath: '/view/home/formarReport'
    description: 'report'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/formarReport/formarReport.html'
  - httpmethod: 'get'                       # 山昆报表导出
    routepath: '/view/home/skReport'
    description: 'report'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
  - httpmethod: 'get'                       # 河北报表导出
    routepath: '/view/home/hbReport'
    description: 'hbReport'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/hbReport/hbReport.html'
  - httpmethod: 'get'                       # 履约报表
    routepath: '/view/home/agree'
    description: 'agree'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/agree/agree.html'
  - httpmethod: 'get'                       # 回访报表
    routepath: '/view/home/visit'
    description: 'visit'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/visit/visit.html'
  - httpmethod: 'get'                       # 回访报表
    routepath: '/view/home/materiel/gift'
    description: 'visit'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/materiel/gift.html'
  - httpmethod: 'get'                       # 盗扫明细查询
    routepath: '/view/home/operateTools/sweepDetail'
    description: 'sweepDetail'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/operateTools/sweepDetail.html'
  - httpmethod: 'get'                       # 用户标签 标签组合管理
    routepath: '/view/home/usertag/assemble'
    description: 'usertag'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/usertag/assemble.html'
  - httpmethod: 'get'                       # 异常码管理
    routepath: '/view/home/code'
    description: 'usertag'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/code/code.html'
activity:
  - httpmethod: 'get'                       # 活动管理
    routepath: '/view/activity/acts/manageacts'
    description: '活动页面'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/manageacts.html'
  - httpmethod: 'get'                       # 实物奖品领奖明细
    routepath: '/view/activity/acts/mPrizeGotHistory'
    description: '实物奖品领奖明细'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/mPrizeGotHistory.html'
  - httpmethod: 'get'                       # 虚拟奖品领奖明细
    routepath: '/view/activity/acts/vPrizeGotHistory'
    description: '虚拟奖品领奖明细'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/vPrizeGotHistory.html'
  - httpmethod: 'get'                       # 积分领奖明细
    routepath: '/view/activity/acts/integralHistory'
    description: '积分领奖明细'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/integralHistory.html'
  - httpmethod: 'get'                       # 河北会员日活动设置
    routepath: '/view/activity/acts/memberday/setting'
    description: '河北会员日活动设置'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/memberday/setting.html'
  - httpmethod: 'get'                       # 河北会员日中奖信息
    routepath: '/view/activity/acts/memberday/detail'
    description: '河北会员日中奖信息'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/memberday/detail.html'
  - httpmethod: 'get'                       # 毛五活动管理
    routepath: '/view/activity/acts/sauce/actmanage'
    description: '毛五活动管理'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/sauce/actmanage.html'
  - httpmethod: 'get'                       # 毛五订单管理
    routepath: '/view/activity/acts/sauce/ordermanage'
    description: '河北会员日中奖信息'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/sauce/ordermanage.html'
dealer:
  - httpmethod: 'get'                       # 经销商审核
    routepath: '/view/dealer/review'
    description: 'dealerreview'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'dealer/review.html'
  - httpmethod: 'get'                       # 经销商管理
    routepath: '/view/dealer/manage'
    description: 'dealermanage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'dealer/manage.html'
  - httpmethod: 'get'                       # 经销商订单管理
    routepath: '/view/dealer/dealerordermanage'
    description: 'dealerordermanage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'dealer/dealerordermanage.html'
  - httpmethod: 'get'                       # 提现审核
    routepath: '/view/dealer/presentaudit'
    description: 'dealerordermanage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'dealer/presentaudit.html'
  - httpmethod: 'get'                       # 系统设置
    routepath: '/view/dealer/systemsettings'
    description: 'dealerordermanage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'dealer/systemsettings.html'
product:
  - httpmethod: 'get'                       # 礼品管理
    routepath: '/view/product/materiel/gift'
    description: 'gift'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/materiel/gift.html'
  - httpmethod: 'get'                       # 红包管理
    routepath: '/view/product/materiel/packet'
    description: 'packet'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/materiel/packet.html'
  - httpmethod: 'get'                       # 积分管理
    routepath: '/view/product/materiel/integration'
    description: 'integration'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/materiel/integration.html'
  - httpmethod: 'get'                       # 供应商管理
    routepath: '/view/product/supply'
    description: 'supply'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/supply/supply.html'
  - httpmethod: 'get'                       # 卷烟管理
    routepath: '/view/product/cigamanage'
    description: 'supply'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/cigamanage/cigarettemanage.html'
visitManage:
  - httpmethod: 'get'                       # 零售户审核管理
    routepath: '/view/visit/reviewmanage'
    description: 'reviewmanage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/reviewmanage.html'
  - httpmethod: 'get'                       # 零售户管理
    routepath: '/view/visit/manage'
    description: 'manage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/manage.html'
  - httpmethod: 'get'                       # 订单管理
    routepath: '/view/visit/ordermanage'
    description: 'manage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/ordermanage.html'
  - httpmethod: 'get'                       # 返佣管理 - 扫码入库
    routepath: '/view/visit/rebate/storagemanage'
    description: 'manage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/storagemanage.html'
  - httpmethod: 'get'                       # 返佣管理 - 扫码返佣
    routepath: '/view/visit/rebate/rebatemanage'
    description: 'manage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/rebatemanage.html'
  - httpmethod: 'get'                       # 其他系统设置
    routepath: '/view/visit/other'
    description: 'other'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/other.html'
  - httpmethod: 'get'                       #提现审核
    routepath: '/view/visit/amountexamine'
    description: 'amountexamine'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/amountexamine.html'
  - httpmethod: 'get'                       #提现审核
    routepath: '/view/visit/achievement'
    description: 'achievement'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/achievement.html'
system:
  - httpmethod: 'get'                       # 修改密码
    routepath: '/view/system/pwd'
    description: 'password'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/account/pwd.html'
  - httpmethod: 'get'                       # 角色管理
    routepath: '/view/system/role'
    description: 'role'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/account/role.html'
  - httpmethod: 'get'                       # 用户管理
    routepath: '/view/system/user'
    description: 'user'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/account/user.html'
  - httpmethod: 'get'                       # 日志记录
    routepath: '/view/system/logs'
    description: 'logs'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/account/logs.html'
  - httpmethod: 'get'                       # 广告位管理
    routepath: '/view/system/adsense'
    description: 'adsense'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/ads/adsense.html'
  - httpmethod: 'get'                       # 广告资源管理
    routepath: '/view/system/source'
    description: 'source'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/ads/source.html'
  - httpmethod: 'get'                       # 客户接口设置
    routepath: '/view/system/interface'
    description: 'interface'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/customer/interface.html'
  - httpmethod: 'get'                       # 客户支付设置
    routepath: '/view/system/pay'
    description: 'pay'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/customer/pay.html'
  - httpmethod: 'get'                       # 风格设置
    routepath: '/view/system/style'
    description: 'style'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'system/style/style.html'