# Author: liubin
# Create Date: 2017-06-21
# Description: view
#
# 接口控制格式 参数说明
# login: 登陆模块
# index: 首页模块
# httpmethod: 请求类型
# routepath: 请求接口
# authorized: 是否已授权
# description: 接口描述
# enableroute: 是否已废弃
# responetype: 接口返回格式
# staticfile: 文件名称
#
login:                                      # 登录
  - httpmethod: 'get'
    routepath: '/login'
    description: '登陆页面'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'login.html'
  - httpmethod: 'get'                       # 找回密码
    routepath: '/find'
    description: '登陆页面'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'find.html'
home:                                       # 首页
  - httpmethod: 'get'                       # KPI
    routepath: '/view/home/kpi'
    description: 'kpi'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/kpi/kpi.html'
  - httpmethod: 'get'                       # KPI
    routepath: '/view/home/henan-kpi'
    description: 'kpi'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/kpi/kpi-henan.html'
  - httpmethod: 'get'                       # 主题查询[规格]
    routepath: '/view/home/theme/spec'
    description: 'theme'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/theme/spec.html'
  - httpmethod: 'get'                       # 主题查询[地域]
    routepath: '/view/home/theme/region'
    description: 'theme'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/theme/region.html'
  - httpmethod: 'get'                       # 多维查询
    routepath: '/view/home/multi'
    description: 'multidimension'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/multi/multi.html'
  - httpmethod: 'get'                       # 活动实时跟踪
    routepath: '/view/home/realtime'
    description: 'realtime'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/track/realtime.html'
  - httpmethod: 'get'                       # 用户群体分析
    routepath: '/view/home/user/group'
    description: 'user'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/user/group.html'
  - httpmethod: 'get'                       # 用户全息画像s
    routepath: '/view/home/user/portrait'
    description: 'user'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/user/portrait.html'
  - httpmethod: 'get'                       # 活动日常分析
    routepath: '/view/home/dayanalysis'
    description: 'dayanalysis'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/track/dayanalysis.html'
  - httpmethod: 'get'                       # 页面路径转化信息
    routepath: '/view/home/pathdetail'
    description: 'pathdetail'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/track/pathdetail.html'
  - httpmethod: 'get'                       # 零售户
    routepath: '/view/home/retailer/overview'
    description: 'retailer'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/retailer/overview.html'
  - httpmethod: 'get'                       # 零售户详情
    routepath: '/view/home/retailer/detail'
    description: 'retailer'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/retailer/detail.html'
  - httpmethod: 'get'                       # 报表导出
    routepath: '/view/home/report'
    description: 'report'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/report/report.html'
  - httpmethod: 'get'                       # 履约报表
    routepath: '/view/home/agree'
    description: 'agree'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/agree/agree.html'
  - httpmethod: 'get'                       # 回访报表
    routepath: '/view/home/visit'
    description: 'visit'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/visit/visit.html'
  - httpmethod: 'get'                       # 回访报表
    routepath: '/view/home/materiel/gift'
    description: 'visit'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'home/materiel/gift.html'
activity:
  - httpmethod: 'get'                       # 活动管理
    routepath: '/view/activity/acts/manageActs'
    description: '活动页面'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/manageActs.html'
  - httpmethod: 'get'                       # 实物奖品领奖明细
    routepath: '/view/activity/acts/mPrizeGotHistory'
    description: '实物奖品领奖明细'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/mPrizeGotHistory.html'
  - httpmethod: 'get'                       # 虚拟奖品领奖明细
    routepath: '/view/activity/acts/vPrizeGotHistory'
    description: '虚拟奖品领奖明细'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/vPrizeGotHistory.html'
  - httpmethod: 'get'                       # 积分领奖明细
    routepath: '/view/activity/acts/integralHistory'
    description: '积分领奖明细'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'activity/acts/integralHistory.html'
product:
  - httpmethod: 'get'                       # 礼品管理
    routepath: '/view/product/materiel/gift'
    description: 'gift'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/materiel/gift.html'
  - httpmethod: 'get'                       # 红包管理
    routepath: '/view/product/materiel/packet'
    description: 'packet'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/materiel/packet.html'
  - httpmethod: 'get'                       # 积分管理
    routepath: '/view/product/materiel/integration'
    description: 'integration'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/materiel/integration.html'  
  - httpmethod: 'get'                       # 供应商管理
    routepath: '/view/product/supply'
    description: 'supply'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/supply/supply.html'
  - httpmethod: 'get'                       # 卷烟管理
    routepath: '/view/product/cigamanage'
    description: 'supply'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'product/cigamanage/cigarettemanage.html'  
visitManage:
  - httpmethod: 'get'                       # 零售户管理
    routepath: '/view/visit/manage'
    description: 'manage'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/manage/manage.html'
  - httpmethod: 'get'                       # 零售户奖励设置
    routepath: '/view/visit/reward'
    description: 'reward'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/reward/reward.html'
  - httpmethod: 'get'                       # 零售户业绩
    routepath: '/view/visit/achievement'
    description: 'achievement'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/achievement/achievement.html'
  - httpmethod: 'get'                       # 零售户获奖统计
    routepath: '/view/visit/winCount'
    description: 'winCount'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/winCount/winCount.html'
  - httpmethod: 'get'                       # 零售户获奖统计
    routepath: '/view/visit/detail'
    description: 'detail'
    enableroute: 1
    responetype: 'html'
    gatewaytype: 0
    staticfile: 'visit/detail/detail.html'
